services:
  mysql:
    image: mysql:8.0
    container_name: fraud-detection-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fraud_detection
    ports:
      - "3306:3306"
    volumes:
      - fraud_detection_mysql_data:/var/lib/mysql

volumes:
  fraud_detection_mysql_data:
